### ISSUE TITLE
6.1 Update

### ISSUE THREAD

**Issue by Evolutious** [r00telement/PlayerTags#9]
Good day - Just opening a ticket as an ask if you are planning to update for 6.1? Dalamud updated to API6 and requires that on mods to be allowed to work. 

Thanks!

**Comment by ryankhart** [comment]
@Evolutious If you're comfortable with learning some basic Visual Studio (you don't even have to learn coding), I just managed to download this project into Visual Studio (not to be confused with VS Code), changed the "2.1.5" to a "2.1.6" in the PlayerTags\PlayerTags\PlayerTags.csproj file, saved the file, and then when to the menu bar, clicked Build->Build Solution. The Player Tags project creator has it automatically build to %appdata%\Roaming\XIVLauncher\devPlugins. Find it in your Windows File Explorer, copy the full file path, and paste it into the Dalamud Settings window in-game in the Experimental tab under Dev Plugin Locations. Then, in the /xlplugins window, you should now see an option called "DevTools" where you can install plugins from that dev folder.

Before:
```
<PackageReference Include="DalamudPackager" Version="2.1.7" />
```

After:
```
<PackageReference Include="DalamudPackager" Version="2.1.7" />
```

I'd make a pull request, but I doubt it would help this to get updated to patch 6.1 any sooner since accepting a pull request would take about the same time as updating this line.

Edit: Updated 2.1.6 to 2.1.7

**Comment by Evolutious** [comment]
> @Evolutious If you're comfortable with learning some basic Visual Studio (you don't even have to learn coding), I just managed to download this project into Visual Studio (not to be confused with VS Code), changed the "2.1.5" to a "2.1.6" in the PlayerTags\PlayerTags\PlayerTags.csproj file, saved the file, and then when to the menu bar, clicked Build->Build Solution. The Player Tags project creator has it automatically build to %appdata%\Roaming\XIVLauncher\devPlugins. Find it in your Windows File Explorer, copy the full file path, and paste it into the Dalamud Settings window in-game in the Experimental tab under Dev Plugin Locations. Then, in the /xlplugins window, you should now see an option called "DevTools" where you can install plugins from that dev folder.
> 
> Before:
> 
> ```
> <PackageReference Include="DalamudPackager" Version="2.1.5" />
> ```
> 
> After:
> 
> ```
> <PackageReference Include="DalamudPackager" Version="2.1.6" />
> ```
> 
> I'd make a pull request, but I doubt it would help this to get updated to patch 6.1 any sooner since accepting a pull request would take about the same time as updating this line.

oh bet! I will give this a go and see how it works out. thank you! :D

**Comment by Evolutious** [comment]
Oh! I forgot about this one. I actually found an even easier way to fix this for me. Just open the JSON in notepad and change "DalamudApiLevel" from 5 to 6. Save and the mod loads just fine.

**Comment by ryankhart** [comment]
> Oh! I forgot about this one. I actually found an even easier way to fix this for me. Just open the JSON in notepad and change "DalamudApiLevel" from 5 to 6. Save and the mod loads just fine.

Oh really? I tried searching for that exact thing "DalamudApiLevel" in this project, and I didn't find it here. I'm just getting my feet wet with plugin development, so I don't know a whole lot yet. I've seen some developers' push commits doing as you say, but others have removed that line altogether and did as I described above.

I bet I'll have a much better understanding once I start developing my own plugin from scratch. All my experience so far as been contributing to other people's existing plugins.

**Comment by ryankhart** [comment]
Oh it's in the actual build! Not the source code! Gotcha! I learned something new. Thanks!

**Comment by ryankhart** [comment]
Ok a word of warning to anyone else reading this that it seems like incrementing the build DalamudApiLevel number from 5 to 6 on a mass scale for your installed plugins may be a bad idea. I just tried it out, and my game crashed on character login. So, try 1 at a time to test each one.

**Comment by Zereah** [comment]
> Oh! I forgot about this one. I actually found an even easier way to fix this for me. Just open the JSON in notepad and change "DalamudApiLevel" from 5 to 6. Save and the mod loads just fine.

Just wanted to give my thanks for giving this tip to get it up and running. Hopefully r00t returns for a proper update but until then we'll have to hope this fix holds for awhile.

**Comment by ryankhart** [comment]
I'm going to leave a link to a Gist I wrote that will hopefully help anyone who finds this be able to download the source code and build this for themselves.
https://gist.github.com/ryankhart/4700481a56bb35c970835e04c13a05ac

**Comment by NadyaNayme** [comment]
> I'm going to leave a link to a Gist I wrote that will hopefully help anyone who finds this be able to download the source code and build this for themselves. https://gist.github.com/ryankhart/4700481a56bb35c970835e04c13a05ac

Word of advice coming from a different plugin developer (Tidy Chat):

 Please, please don't do this.

It'll work for some plugins but many plugins require much more changes than a simple API bump which is _why_ the API gets bumped to disable all plugins. Signatures that a plugin relies on to work could have changed in an update and most plugins where this is an issue will either not actually work or simply crash your client when trying to load. If any structs or data has been changed it could even result in sending invalid information to the server like when Chat2 started the Chocobo Race Timer when trying to swap to a Linkshell with the keybind since it accessed the function via an array index in ClientStructs and that index had been changed so it was calling the completely wrong function.

Plugins get disabled to protect users until the developer(s) have time to check their plugins for any issues a patch may have caused. While Square is currently seemingly pretty lax with things potentially making yourself _trivially detectable_ greatly increases the odds of you catching a ban.

**Comment by ryankhart** [comment]
> If any structs or data has been changed it could even result in sending invalid information to the server like when Chat2...

Thanks for your tactful and helpful advice and for a specific example. I'm still learning all this myself. I'll go find Chat 2 and try to learn more about it from the commits for API 6. From my perspective, I could only imagine the plugins that I have manually updated to be fully clientside, so my goal here is to learn what a server call looks like from a plugin's source code so I can spot issues before blindly updating the API version.

Edit: Oh, this is still an ongoing issue, as I noticed that Chat 2 was taken down again. I guess I'll have to wait for an update to see how that kind of thing is fixed.

Edit Edit: Oh, I just downloaded Chat 2 from an unofficial repo, and I can already tell just from a user perspective that this plugin makes server calls because it completely replaces the chat box with an ImGui window, which would have to make server calls. For some reason, I had thought that it was already in the official repo, but that was just because of the announement of its release in Discord.
